<? 
$pagename="books";
$title=LIBRI;
$singolo=LIBRO;
$keywords=LIBRI.",".LIBRO.",".SCIENCE.",freescience,gratis,free";

$campi[]="id_links";
$campi[]="id_categoria";
$campi[]="url";
$campi[]="langue";
$campi[]="it";
$campi[]="en";
$campi[]="titolo";
$campi[]="autore";
$campi[]="formato";
$campi[]="pagine";
$campi[]="img";
$campi[]="active";
$campi[]="data";
$campi[]="cat2";
$campi[]="click";
$campi[]="year";
$campi[]="linkautore";

$getcampi[]="id_links";
$getcampi[]="url";
$getcampi[]="langue";
$getcampi[]="titolo";
$getcampi[]="autore";
$getcampi[]="formato";
$getcampi[]="pagine";
$getcampi[]="img";
$getcampi[]="cat2";
$getcampi[]="click";
$getcampi[]="id_categoria";
$getcampi[]="year";
$getcampi[]="linkautore";
?>
